inherit_from: .rubocop_todo.yml

require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-performance


Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: single_quotes
  Enabled: true

RSpec/NestedGroups:
  Max: 4

Metrics/BlockLength:
  Exclude:
    - '**/*.gemspec'
    - 'spec/**/**'

RSpec/MultipleExpectations:
  Max: 2
